joint_limits:
  l_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: true
    max_acceleration: 6.6
  l_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: true
    max_acceleration: 6.6
  l_gripper_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  l_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  l_gripper_motor_screw_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  l_gripper_motor_slider_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  l_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: true
    max_acceleration: 4.176
  l_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: true
    max_acceleration: 4.164
  l_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: true
    max_acceleration: 6.54
  l_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: true
    max_acceleration: 6.146
  l_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: true
    max_acceleration: 7.2
  r_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  r_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  r_gripper_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  r_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  r_gripper_motor_screw_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  r_gripper_motor_slider_joint:
    has_velocity_limits: true
    max_velocity: 12.8
    has_acceleration_limits: true
    max_acceleration: 12.8
  r_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.52
    has_acceleration_limits: true
    max_acceleration: 1.52
  r_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  r_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  r_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  r_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.5

velocity_limit_factor: 1
